HW
asilaheyy/TestingHomework pull request #1
Opened 2023-02-16 18:46 UTC by asilaheyy

2023-02-17 18:05 UTC, alekseykoshelev commented on src/main/java/org/example/testing/User.java
> +            passedUserEMail = "Empty email";
Лучше сделать эти проверки так, чтобы они выбрасывали эксепшн, вместо вот этого присваивания. Эти проверки нужно будет вызвать в конструкторе. Сейчас по сути эти проверки никак не работают, потому что я могу передать в конструктор любые значения. 

Ну и в тестах можно будет проверить через `assertThrows`

2023-02-17 19:18 UTC, OlgaLugacheva requested changes

2023-02-17 19:18 UTC, OlgaLugacheva commented on src/main/java/org/example/testing/UserRepository.java
> +                userExists = users.stream().anyMatch(u -> u.equals(givenUserName))
например, посожет filter 

` return users.stream().filter(u -> u.getUserName().equals(givenUserName) && u.getUserPassw().equals(givenPassw)).findFirst();`

2023-02-20 20:15 UTC, alekseykoshelev requested changes

2023-02-20 20:15 UTC, alekseykoshelev commented on src/main/java/org/example/testing/User.java
> +    public String userNameNotNull(String passedUserName) {
Эти методы можно сделать `void` и вызывать их в начале конструктора, потому что в конструкторе у тебя по сути такие же проверки и делают, нет смысла дублировать код. Вот так 
```
userNameNotNull(userName);
emailNotNull(userEmail);
```
а уже после этих проверок сделать присвоение в поля. Также в тестах можно вызовы этих методов заменить на вызовы конструктора. Это относится ко всем 4 методам проверки.

2023-02-20 20:15 UTC, alekseykoshelev commented on src/test/java/org/example/testing/UserTest.java
> +        assertThrows(EmailException.class, () -> user.emailNotNull(""));
Тут вместо вызова методов можно будет просто создавать юзера с невалидными параметрами. `new User(...);`

2023-02-20 20:15 UTC, alekseykoshelev commented on src/main/java/org/example/testing/User.java
> +
По условиям задачи нужно еще создать конструктор без аргументов и написать на него тест.

2023-03-02 09:19 UTC, OlgaLugacheva requested changes

2023-03-02 09:19 UTC, OlgaLugacheva commented on src/test/java/org/example/testing/UserRepositoryTest.java
> +            userRepository.getAllUsers().stream().toList();
по сути это не тест, потому что тест - это когда мы выполняем какой-то метод и сравниваем результат его выполнения с ожидаемыми результатми, например, этот метод можно преписать так

```
    @Test
    @DisplayName("When there are users in repository, repository returns users list.")
    public void getAllUsersTest() {
        if (userRepository != null) {
            userRepository.addUser(user1);
            Assertions.assertIterableEquals(userRepository.getAllUsers(), List.of(user1));
        } else {
            throw new UserNotFoundException("Список пользователей пуст.");
        }
    }
```

2023-03-28 15:28 UTC, merged